
package user.stories.part.d;

import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import user.stories.part.d.checktime;



public class userstoriesd extends javax.swing.JFrame {


    public userstoriesd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        orderlbl = new javax.swing.JLabel();
        ordernolbl = new javax.swing.JLabel();
        namelbl = new javax.swing.JLabel();
        jorderno = new javax.swing.JTextField();
        jname = new javax.swing.JTextField();
        phonenolbl = new javax.swing.JLabel();
        jphoneno = new javax.swing.JTextField();
        checkButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Remaining time for your order to arrive");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        orderlbl.setBackground(new java.awt.Color(255, 255, 255));
        orderlbl.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        orderlbl.setText("Checking for the remaining time your orders to arrive!");
        orderlbl.setPreferredSize(new java.awt.Dimension(400, 20));
        getContentPane().add(orderlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 510, 30));
        orderlbl.getAccessibleContext().setAccessibleName("Checking for the remaining time your orders to arrive!");

        ordernolbl.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        ordernolbl.setText("Order No:");
        getContentPane().add(ordernolbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        namelbl.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        namelbl.setText("Name:");
        getContentPane().add(namelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 22));

        jorderno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jordernoActionPerformed(evt);
            }
        });
        getContentPane().add(jorderno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 204, -1));

        jname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnameActionPerformed(evt);
            }
        });
        jname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jnameKeyTyped(evt);
            }
        });
        getContentPane().add(jname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 204, -1));

        phonenolbl.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        phonenolbl.setText("Phone Number:");
        getContentPane().add(phonenolbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jphoneno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jphonenoActionPerformed(evt);
            }
        });
        jphoneno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jphonenoKeyTyped(evt);
            }
        });
        getContentPane().add(jphoneno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 204, -1));

        checkButton.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        checkButton.setText("Check");
        checkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkButtonActionPerformed(evt);
            }
        });
        getContentPane().add(checkButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        resetButton.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        getContentPane().add(resetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, -1, -1));

        cancelButton.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user/stories/part/d/c1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jphonenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jphonenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jphonenoActionPerformed

    private void jordernoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jordernoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jordernoActionPerformed
    
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        jorderno.setText("");
        jname.setText("");
        jphoneno.setText("");
        
    }//GEN-LAST:event_resetButtonActionPerformed

    private void jnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnameActionPerformed
       
    }//GEN-LAST:event_jnameActionPerformed

    private void jnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jnameKeyTyped
        // TODO add your handling code here:
        
        char jname = evt.getKeyChar();
        
        if(!(Character.isAlphabetic(jname) || (jname== KeyEvent.VK_BACK_SPACE) || (jname== KeyEvent.VK_DELETE)))
            evt.consume();
                
    }//GEN-LAST:event_jnameKeyTyped

    private void jphonenoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jphonenoKeyTyped
        // TODO add your handling code here:
        int phoneno;
        
        try {
            phoneno = Integer.parseInt(jphoneno.getText());
        }
        catch(NumberFormatException e){
            jphoneno.setText("");
            
           
        }               
        
    }//GEN-LAST:event_jphonenoKeyTyped

    private void checkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkButtonActionPerformed
        // TODO add your handling code here:
        
        
        String phoneno = jphoneno.getText();
        String name = jname.getText();
        String orderno = jorderno.getText();
        
        if(orderno.equals("AL") && name.equals("Lee") && "0123456789".equals(phoneno))
        {
            jorderno.setText(null);
            jname.setText(null);
            jphoneno.setText(null);
            systemExit();
            
            checktime Info = new checktime();
            Info.setVisible(true);
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Invalid input","Error",JOptionPane.ERROR_MESSAGE);
            jorderno.setText(null);
            jname.setText(null);
            jphoneno.setText(null);
        }
           
    }//GEN-LAST:event_checkButtonActionPerformed

private void systemExit()
{
WindowEvent Windowclosing = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);

}

    /**
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userstoriesd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userstoriesd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userstoriesd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userstoriesd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userstoriesd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton checkButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jname;
    private javax.swing.JTextField jorderno;
    private javax.swing.JTextField jphoneno;
    private javax.swing.JLabel namelbl;
    private javax.swing.JLabel orderlbl;
    private javax.swing.JLabel ordernolbl;
    private javax.swing.JLabel phonenolbl;
    private javax.swing.JButton resetButton;
    // End of variables declaration//GEN-END:variables
}

